# Generated by Django 5.2.4 on 2025-07-29 21:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crypto_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="subscription",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="crypto_app.subscriptionplan",
            ),
            preserve_default=False,
        ),
    ]
