# Generated by Django 5.2.4 on 2025-07-29 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("crypto_app", "0003_user_bio_user_profile_picture_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="subscription",
        ),
        migrations.RemoveField(
            model_name="user",
            name="subscription_end_date",
        ),
        migrations.RemoveField(
            model_name="user",
            name="subscription_start_date",
        ),
    ]
