# Generated by Django 5.2.4 on 2025-07-29 22:07

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crypto_app", "0004_remove_user_subscription_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="subscription",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="crypto_app.subscriptionplan",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="subscription_end_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="subscription_start_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
