# Generated by Django 5.2.4 on 2025-07-31 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crypto_app", "0005_user_subscription_user_subscription_end_date_and_more"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[],
        ),
        migrations.AlterField(
            model_name="payment",
            name="status",
            field=models.CharField(
                choices=[("P", "pending"), ("C", "complete"), ("F", "failed")],
                default="P",
                max_length=30,
            ),
        ),
    ]
